# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode_scanner', '__first__'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_cart', to='barcode_scanner.Product')),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_of_user', to='login.User')),
            ],
        ),
    ]
