# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
    ]
