# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_scanner', '__first__'),
        ('cart', '0002_remove_cart_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products_added',
        ),
        migrations.AddField(
            model_name='cart',
            name='products_added',
            field=models.ManyToManyField(related_name='products_in_cart', to='barcode_scanner.Product'),
        ),
    ]
