# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='barcode.png', upload_to='/media'),
            preserve_default=False,
        ),
    ]
